# Generated by Django 5.2 on 2025-05-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField(help_text='Price in cents (e.g., 7900 for $79.00)')),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in the plan')),
                ('stripe_price_id', models.CharField(help_text='Stripe Price ID (e.g., price_xxxxxxxxxxxx)', max_length=255, unique=True)),
                ('trial_period_days', models.PositiveIntegerField(default=0, help_text='Number of trial days (0 for no trial)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for new subscriptions')),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular for highlighting in UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
