/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface BlogComment
 */
export interface BlogComment {
    /**
     * 
     * @type {number}
     * @memberof BlogComment
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof BlogComment
     */
    post?: number;
    /**
     * 
     * @type {User}
     * @memberof BlogComment
     */
    readonly user: User;
    /**
     * 
     * @type {string}
     * @memberof BlogComment
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogComment
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogComment
     */
    content: string;
    /**
     * Comments must be approved to be publicly visible
     * @type {boolean}
     * @memberof BlogComment
     */
    readonly approved: boolean;
    /**
     * 
     * @type {Date}
     * @memberof BlogComment
     */
    readonly createdAt: Date;
}

/**
 * Check if a given object implements the BlogComment interface.
 */
export function instanceOfBlogComment(value: object): value is BlogComment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('approved' in value) || value['approved'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function BlogCommentFromJSON(json: any): BlogComment {
    return BlogCommentFromJSONTyped(json, false);
}

export function BlogCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogComment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'post': json['post'] == null ? undefined : json['post'],
        'user': UserFromJSON(json['user']),
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'content': json['content'],
        'approved': json['approved'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function BlogCommentToJSON(json: any): BlogComment {
    return BlogCommentToJSONTyped(json, false);
}

export function BlogCommentToJSONTyped(value?: Omit<BlogComment, 'id'|'user'|'approved'|'created_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'post': value['post'],
        'name': value['name'],
        'email': value['email'],
        'content': value['content'],
    };
}

