/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryEnum } from './CategoryEnum';
import {
    CategoryEnumFromJSON,
    CategoryEnumFromJSONTyped,
    CategoryEnumToJSON,
    CategoryEnumToJSONTyped,
} from './CategoryEnum';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface BlogPostList
 */
export interface BlogPostList {
    /**
     * 
     * @type {number}
     * @memberof BlogPostList
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof BlogPostList
     */
    title: string;
    /**
     * Unique URL-friendly identifier (leave blank to auto-generate)
     * @type {string}
     * @memberof BlogPostList
     */
    readonly slug: string;
    /**
     * A short summary of the post (optional)
     * @type {string}
     * @memberof BlogPostList
     */
    excerpt?: string | null;
    /**
     * URL of the main image for the post
     * @type {string}
     * @memberof BlogPostList
     */
    coverImage?: string | null;
    /**
     * 
     * @type {User}
     * @memberof BlogPostList
     */
    readonly author: User;
    /**
     * 
     * @type {CategoryEnum}
     * @memberof BlogPostList
     */
    category?: CategoryEnum;
    /**
     * List of tags, e.g., ['manicure', 'trends']
     * @type {any}
     * @memberof BlogPostList
     */
    tags?: any | null;
    /**
     * Check this to make the post visible to the public
     * @type {boolean}
     * @memberof BlogPostList
     */
    published?: boolean;
    /**
     * Check this to feature the post (e.g., on homepage)
     * @type {boolean}
     * @memberof BlogPostList
     */
    featured?: boolean;
    /**
     * Optional: Set a future date/time to publish
     * @type {Date}
     * @memberof BlogPostList
     */
    publishedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof BlogPostList
     */
    readonly viewCount: number;
    /**
     * 
     * @type {Date}
     * @memberof BlogPostList
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof BlogPostList
     */
    readonly commentsCount: number;
}



/**
 * Check if a given object implements the BlogPostList interface.
 */
export function instanceOfBlogPostList(value: object): value is BlogPostList {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('viewCount' in value) || value['viewCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('commentsCount' in value) || value['commentsCount'] === undefined) return false;
    return true;
}

export function BlogPostListFromJSON(json: any): BlogPostList {
    return BlogPostListFromJSONTyped(json, false);
}

export function BlogPostListFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostList {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'slug': json['slug'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'author': UserFromJSON(json['author']),
        'category': json['category'] == null ? undefined : CategoryEnumFromJSON(json['category']),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'published': json['published'] == null ? undefined : json['published'],
        'featured': json['featured'] == null ? undefined : json['featured'],
        'publishedAt': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
        'viewCount': json['view_count'],
        'createdAt': (new Date(json['created_at'])),
        'commentsCount': json['comments_count'],
    };
}

export function BlogPostListToJSON(json: any): BlogPostList {
    return BlogPostListToJSONTyped(json, false);
}

export function BlogPostListToJSONTyped(value?: Omit<BlogPostList, 'id'|'slug'|'author'|'view_count'|'created_at'|'comments_count'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'excerpt': value['excerpt'],
        'cover_image': value['coverImage'],
        'category': CategoryEnumToJSON(value['category']),
        'tags': value['tags'],
        'published': value['published'],
        'featured': value['featured'],
        'published_at': value['publishedAt'] == null ? undefined : ((value['publishedAt'] as any).toISOString()),
    };
}

