/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `nail_art` - Nail Art
 * * `marketing` - Marketing
 * * `business_advice` - Business Advice
 * * `trends` - Trends
 * * `product_reviews` - Product Reviews
 * * `tutorials` - Tutorials
 * * `other` - Other
 * @export
 */
export const CategoryEnum = {
    NailArt: 'nail_art',
    Marketing: 'marketing',
    BusinessAdvice: 'business_advice',
    Trends: 'trends',
    ProductReviews: 'product_reviews',
    Tutorials: 'tutorials',
    Other: 'other'
} as const;
export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];


export function instanceOfCategoryEnum(value: any): boolean {
    for (const key in CategoryEnum) {
        if (Object.prototype.hasOwnProperty.call(CategoryEnum, key)) {
            if (CategoryEnum[key as keyof typeof CategoryEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CategoryEnumFromJSON(json: any): CategoryEnum {
    return CategoryEnumFromJSONTyped(json, false);
}

export function CategoryEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryEnum {
    return json as CategoryEnum;
}

export function CategoryEnumToJSON(value?: CategoryEnum | null): any {
    return value as any;
}

export function CategoryEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): CategoryEnum {
    return value as CategoryEnum;
}

