/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for password change endpoint.
 * @export
 * @interface ChangePassword
 */
export interface ChangePassword {
    /**
     * 
     * @type {string}
     * @memberof ChangePassword
     */
    currentPassword: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePassword
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePassword
     */
    newPassword2: string;
}

/**
 * Check if a given object implements the ChangePassword interface.
 */
export function instanceOfChangePassword(value: object): value is ChangePassword {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('newPassword2' in value) || value['newPassword2'] === undefined) return false;
    return true;
}

export function ChangePasswordFromJSON(json: any): ChangePassword {
    return ChangePasswordFromJSONTyped(json, false);
}

export function ChangePasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePassword {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['current_password'],
        'newPassword': json['new_password'],
        'newPassword2': json['new_password2'],
    };
}

export function ChangePasswordToJSON(json: any): ChangePassword {
    return ChangePasswordToJSONTyped(json, false);
}

export function ChangePasswordToJSONTyped(value?: ChangePassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_password': value['currentPassword'],
        'new_password': value['newPassword'],
        'new_password2': value['newPassword2'],
    };
}

