/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `notContacted` - Not Contacted
 * * `contacted` - Contacted
 * * `interested` - Interested
 * * `notInterested` - Not Interested
 * * `subscribed` - Subscribed
 * @export
 */
export const ContactStatusEnum = {
    NotContacted: 'notContacted',
    Contacted: 'contacted',
    Interested: 'interested',
    NotInterested: 'notInterested',
    Subscribed: 'subscribed'
} as const;
export type ContactStatusEnum = typeof ContactStatusEnum[keyof typeof ContactStatusEnum];


export function instanceOfContactStatusEnum(value: any): boolean {
    for (const key in ContactStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(ContactStatusEnum, key)) {
            if (ContactStatusEnum[key as keyof typeof ContactStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ContactStatusEnumFromJSON(json: any): ContactStatusEnum {
    return ContactStatusEnumFromJSONTyped(json, false);
}

export function ContactStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactStatusEnum {
    return json as ContactStatusEnum;
}

export function ContactStatusEnumToJSON(value?: ContactStatusEnum | null): any {
    return value as any;
}

export function ContactStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ContactStatusEnum {
    return value as ContactStatusEnum;
}

