/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Salon } from './Salon';
import {
    SalonFromJSON,
    SalonFromJSONTyped,
    SalonToJSON,
    SalonToJSONTyped,
} from './Salon';

/**
 * 
 * @export
 * @interface PaginatedSalonList
 */
export interface PaginatedSalonList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSalonList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSalonList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSalonList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Salon>}
     * @memberof PaginatedSalonList
     */
    results: Array<Salon>;
}

/**
 * Check if a given object implements the PaginatedSalonList interface.
 */
export function instanceOfPaginatedSalonList(value: object): value is PaginatedSalonList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedSalonListFromJSON(json: any): PaginatedSalonList {
    return PaginatedSalonListFromJSONTyped(json, false);
}

export function PaginatedSalonListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSalonList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(SalonFromJSON)),
    };
}

export function PaginatedSalonListToJSON(json: any): PaginatedSalonList {
    return PaginatedSalonListToJSONTyped(json, false);
}

export function PaginatedSalonListToJSONTyped(value?: PaginatedSalonList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(SalonToJSON)),
    };
}

