/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionPlan } from './SubscriptionPlan';
import {
    SubscriptionPlanFromJSON,
    SubscriptionPlanFromJSONTyped,
    SubscriptionPlanToJSON,
    SubscriptionPlanToJSONTyped,
} from './SubscriptionPlan';

/**
 * 
 * @export
 * @interface PaginatedSubscriptionPlanList
 */
export interface PaginatedSubscriptionPlanList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSubscriptionPlanList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSubscriptionPlanList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSubscriptionPlanList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<SubscriptionPlan>}
     * @memberof PaginatedSubscriptionPlanList
     */
    results: Array<SubscriptionPlan>;
}

/**
 * Check if a given object implements the PaginatedSubscriptionPlanList interface.
 */
export function instanceOfPaginatedSubscriptionPlanList(value: object): value is PaginatedSubscriptionPlanList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedSubscriptionPlanListFromJSON(json: any): PaginatedSubscriptionPlanList {
    return PaginatedSubscriptionPlanListFromJSONTyped(json, false);
}

export function PaginatedSubscriptionPlanListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSubscriptionPlanList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(SubscriptionPlanFromJSON)),
    };
}

export function PaginatedSubscriptionPlanListToJSON(json: any): PaginatedSubscriptionPlanList {
    return PaginatedSubscriptionPlanListToJSONTyped(json, false);
}

export function PaginatedSubscriptionPlanListToJSONTyped(value?: PaginatedSubscriptionPlanList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(SubscriptionPlanToJSON)),
    };
}

