/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlogPostList } from './BlogPostList';
import {
    BlogPostListFromJSON,
    BlogPostListFromJSONTyped,
    BlogPostListToJSON,
    BlogPostListToJSONTyped,
} from './BlogPostList';

/**
 * 
 * @export
 * @interface PaginatedBlogPostListList
 */
export interface PaginatedBlogPostListList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedBlogPostListList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBlogPostListList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBlogPostListList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<BlogPostList>}
     * @memberof PaginatedBlogPostListList
     */
    results: Array<BlogPostList>;
}

/**
 * Check if a given object implements the PaginatedBlogPostListList interface.
 */
export function instanceOfPaginatedBlogPostListList(value: object): value is PaginatedBlogPostListList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedBlogPostListListFromJSON(json: any): PaginatedBlogPostListList {
    return PaginatedBlogPostListListFromJSONTyped(json, false);
}

export function PaginatedBlogPostListListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBlogPostListList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(BlogPostListFromJSON)),
    };
}

export function PaginatedBlogPostListListToJSON(json: any): PaginatedBlogPostListList {
    return PaginatedBlogPostListListToJSONTyped(json, false);
}

export function PaginatedBlogPostListListToJSONTyped(value?: PaginatedBlogPostListList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(BlogPostListToJSON)),
    };
}

