/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Template } from './Template';
import {
    TemplateFromJSON,
    TemplateFromJSONTyped,
    TemplateToJSON,
    TemplateToJSONTyped,
} from './Template';

/**
 * 
 * @export
 * @interface PaginatedTemplateList
 */
export interface PaginatedTemplateList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTemplateList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTemplateList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTemplateList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Template>}
     * @memberof PaginatedTemplateList
     */
    results: Array<Template>;
}

/**
 * Check if a given object implements the PaginatedTemplateList interface.
 */
export function instanceOfPaginatedTemplateList(value: object): value is PaginatedTemplateList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedTemplateListFromJSON(json: any): PaginatedTemplateList {
    return PaginatedTemplateListFromJSONTyped(json, false);
}

export function PaginatedTemplateListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTemplateList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TemplateFromJSON)),
    };
}

export function PaginatedTemplateListToJSON(json: any): PaginatedTemplateList {
    return PaginatedTemplateListToJSONTyped(json, false);
}

export function PaginatedTemplateListToJSONTyped(value?: PaginatedTemplateList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(TemplateToJSON)),
    };
}

