/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUserProfileUpdate
 */
export interface PatchedUserProfileUpdate {
    /**
     * 
     * @type {string}
     * @memberof PatchedUserProfileUpdate
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserProfileUpdate
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserProfileUpdate
     */
    phoneNumber?: string | null;
}

/**
 * Check if a given object implements the PatchedUserProfileUpdate interface.
 */
export function instanceOfPatchedUserProfileUpdate(value: object): value is PatchedUserProfileUpdate {
    return true;
}

export function PatchedUserProfileUpdateFromJSON(json: any): PatchedUserProfileUpdate {
    return PatchedUserProfileUpdateFromJSONTyped(json, false);
}

export function PatchedUserProfileUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserProfileUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
    };
}

export function PatchedUserProfileUpdateToJSON(json: any): PatchedUserProfileUpdate {
    return PatchedUserProfileUpdateToJSONTyped(json, false);
}

export function PatchedUserProfileUpdateToJSONTyped(value?: PatchedUserProfileUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'phone_number': value['phoneNumber'],
    };
}

