/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryEnum } from './CategoryEnum';
import {
    CategoryEnumFromJSON,
    CategoryEnumFromJSONTyped,
    CategoryEnumToJSON,
    CategoryEnumToJSONTyped,
} from './CategoryEnum';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { BlogComment } from './BlogComment';
import {
    BlogCommentFromJSON,
    BlogCommentFromJSONTyped,
    BlogCommentToJSON,
    BlogCommentToJSONTyped,
} from './BlogComment';

/**
 * 
 * @export
 * @interface PatchedBlogPost
 */
export interface PatchedBlogPost {
    /**
     * 
     * @type {number}
     * @memberof PatchedBlogPost
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedBlogPost
     */
    title?: string;
    /**
     * Unique URL-friendly identifier (leave blank to auto-generate)
     * @type {string}
     * @memberof PatchedBlogPost
     */
    readonly slug?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedBlogPost
     */
    content?: string;
    /**
     * A short summary of the post (optional)
     * @type {string}
     * @memberof PatchedBlogPost
     */
    excerpt?: string | null;
    /**
     * URL of the main image for the post
     * @type {string}
     * @memberof PatchedBlogPost
     */
    coverImage?: string | null;
    /**
     * 
     * @type {User}
     * @memberof PatchedBlogPost
     */
    readonly author?: User;
    /**
     * 
     * @type {CategoryEnum}
     * @memberof PatchedBlogPost
     */
    category?: CategoryEnum;
    /**
     * List of tags, e.g., ['manicure', 'trends']
     * @type {any}
     * @memberof PatchedBlogPost
     */
    tags?: any | null;
    /**
     * Check this to make the post visible to the public
     * @type {boolean}
     * @memberof PatchedBlogPost
     */
    published?: boolean;
    /**
     * Check this to feature the post (e.g., on homepage)
     * @type {boolean}
     * @memberof PatchedBlogPost
     */
    featured?: boolean;
    /**
     * Optional: Set a future date/time to publish
     * @type {Date}
     * @memberof PatchedBlogPost
     */
    publishedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedBlogPost
     */
    readonly viewCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedBlogPost
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedBlogPost
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Array<BlogComment>}
     * @memberof PatchedBlogPost
     */
    readonly comments?: Array<BlogComment>;
}



/**
 * Check if a given object implements the PatchedBlogPost interface.
 */
export function instanceOfPatchedBlogPost(value: object): value is PatchedBlogPost {
    return true;
}

export function PatchedBlogPostFromJSON(json: any): PatchedBlogPost {
    return PatchedBlogPostFromJSONTyped(json, false);
}

export function PatchedBlogPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedBlogPost {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'content': json['content'] == null ? undefined : json['content'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'author': json['author'] == null ? undefined : UserFromJSON(json['author']),
        'category': json['category'] == null ? undefined : CategoryEnumFromJSON(json['category']),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'published': json['published'] == null ? undefined : json['published'],
        'featured': json['featured'] == null ? undefined : json['featured'],
        'publishedAt': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
        'viewCount': json['view_count'] == null ? undefined : json['view_count'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'comments': json['comments'] == null ? undefined : ((json['comments'] as Array<any>).map(BlogCommentFromJSON)),
    };
}

export function PatchedBlogPostToJSON(json: any): PatchedBlogPost {
    return PatchedBlogPostToJSONTyped(json, false);
}

export function PatchedBlogPostToJSONTyped(value?: Omit<PatchedBlogPost, 'id'|'slug'|'author'|'view_count'|'created_at'|'updated_at'|'comments'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
        'excerpt': value['excerpt'],
        'cover_image': value['coverImage'],
        'category': CategoryEnumToJSON(value['category']),
        'tags': value['tags'],
        'published': value['published'],
        'featured': value['featured'],
        'published_at': value['publishedAt'] == null ? undefined : ((value['publishedAt'] as any).toISOString()),
    };
}

