/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactStatusEnum } from './ContactStatusEnum';
import {
    ContactStatusEnumFromJSON,
    ContactStatusEnumFromJSONTyped,
    ContactStatusEnumToJSON,
    ContactStatusEnumToJSONTyped,
} from './ContactStatusEnum';

/**
 * 
 * @export
 * @interface PatchedSalon
 */
export interface PatchedSalon {
    /**
     * 
     * @type {number}
     * @memberof PatchedSalon
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedSalon
     */
    name?: string;
    /**
     * e.g., City, State or Neighborhood
     * @type {string}
     * @memberof PatchedSalon
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSalon
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedSalon
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedSalon
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedSalon
     */
    description?: string | null;
    /**
     * List of services, e.g., ['Manicure - $30', 'Pedicure - $45']
     * @type {any}
     * @memberof PatchedSalon
     */
    services?: any | null;
    /**
     * e.g., Mon-Fri: 9am-7pm\nSat: 10am-5pm
     * @type {string}
     * @memberof PatchedSalon
     */
    openingHours?: string | null;
    /**
     * Unique URL-friendly identifier (leave blank to auto-generate)
     * @type {string}
     * @memberof PatchedSalon
     */
    sampleUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedSalon
     */
    readonly claimed?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSalon
     */
    readonly claimedAt?: Date | null;
    /**
     * 
     * @type {ContactStatusEnum}
     * @memberof PatchedSalon
     */
    contactStatus?: ContactStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSalon
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSalon
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof PatchedSalon
     */
    readonly owner?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedSalon
     */
    template?: number | null;
}



/**
 * Check if a given object implements the PatchedSalon interface.
 */
export function instanceOfPatchedSalon(value: object): value is PatchedSalon {
    return true;
}

export function PatchedSalonFromJSON(json: any): PatchedSalon {
    return PatchedSalonFromJSONTyped(json, false);
}

export function PatchedSalonFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSalon {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'location': json['location'] == null ? undefined : json['location'],
        'address': json['address'] == null ? undefined : json['address'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'email': json['email'] == null ? undefined : json['email'],
        'description': json['description'] == null ? undefined : json['description'],
        'services': json['services'] == null ? undefined : json['services'],
        'openingHours': json['opening_hours'] == null ? undefined : json['opening_hours'],
        'sampleUrl': json['sample_url'] == null ? undefined : json['sample_url'],
        'claimed': json['claimed'] == null ? undefined : json['claimed'],
        'claimedAt': json['claimed_at'] == null ? undefined : (new Date(json['claimed_at'])),
        'contactStatus': json['contact_status'] == null ? undefined : ContactStatusEnumFromJSON(json['contact_status']),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'owner': json['owner'] == null ? undefined : json['owner'],
        'template': json['template'] == null ? undefined : json['template'],
    };
}

export function PatchedSalonToJSON(json: any): PatchedSalon {
    return PatchedSalonToJSONTyped(json, false);
}

export function PatchedSalonToJSONTyped(value?: Omit<PatchedSalon, 'id'|'claimed'|'claimed_at'|'created_at'|'updated_at'|'owner'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'location': value['location'],
        'address': value['address'],
        'phone_number': value['phoneNumber'],
        'email': value['email'],
        'description': value['description'],
        'services': value['services'],
        'opening_hours': value['openingHours'],
        'sample_url': value['sampleUrl'],
        'contact_status': ContactStatusEnumToJSON(value['contactStatus']),
        'template': value['template'],
    };
}

