/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for password change endpoint.
 * @export
 * @interface PatchedChangePassword
 */
export interface PatchedChangePassword {
    /**
     * 
     * @type {string}
     * @memberof PatchedChangePassword
     */
    currentPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedChangePassword
     */
    newPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedChangePassword
     */
    newPassword2?: string;
}

/**
 * Check if a given object implements the PatchedChangePassword interface.
 */
export function instanceOfPatchedChangePassword(value: object): value is PatchedChangePassword {
    return true;
}

export function PatchedChangePasswordFromJSON(json: any): PatchedChangePassword {
    return PatchedChangePasswordFromJSONTyped(json, false);
}

export function PatchedChangePasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedChangePassword {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['current_password'] == null ? undefined : json['current_password'],
        'newPassword': json['new_password'] == null ? undefined : json['new_password'],
        'newPassword2': json['new_password2'] == null ? undefined : json['new_password2'],
    };
}

export function PatchedChangePasswordToJSON(json: any): PatchedChangePassword {
    return PatchedChangePasswordToJSONTyped(json, false);
}

export function PatchedChangePasswordToJSONTyped(value?: PatchedChangePassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_password': value['currentPassword'],
        'new_password': value['newPassword'],
        'new_password2': value['newPassword2'],
    };
}

