/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentIntentRequest
 */
export interface PaymentIntentRequest {
    /**
     * 
     * @type {number}
     * @memberof PaymentIntentRequest
     */
    amountCents: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentRequest
     */
    currency?: string;
}

/**
 * Check if a given object implements the PaymentIntentRequest interface.
 */
export function instanceOfPaymentIntentRequest(value: object): value is PaymentIntentRequest {
    if (!('amountCents' in value) || value['amountCents'] === undefined) return false;
    return true;
}

export function PaymentIntentRequestFromJSON(json: any): PaymentIntentRequest {
    return PaymentIntentRequestFromJSONTyped(json, false);
}

export function PaymentIntentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentIntentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amountCents': json['amount_cents'],
        'description': json['description'] == null ? undefined : json['description'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function PaymentIntentRequestToJSON(json: any): PaymentIntentRequest {
    return PaymentIntentRequestToJSONTyped(json, false);
}

export function PaymentIntentRequestToJSONTyped(value?: PaymentIntentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_cents': value['amountCents'],
        'description': value['description'],
        'currency': value['currency'],
    };
}

