/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentIntentResponse
 */
export interface PaymentIntentResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentResponse
     */
    clientSecret: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentResponse
     */
    intentId: string;
}

/**
 * Check if a given object implements the PaymentIntentResponse interface.
 */
export function instanceOfPaymentIntentResponse(value: object): value is PaymentIntentResponse {
    if (!('clientSecret' in value) || value['clientSecret'] === undefined) return false;
    if (!('intentId' in value) || value['intentId'] === undefined) return false;
    return true;
}

export function PaymentIntentResponseFromJSON(json: any): PaymentIntentResponse {
    return PaymentIntentResponseFromJSONTyped(json, false);
}

export function PaymentIntentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentIntentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'clientSecret': json['clientSecret'],
        'intentId': json['intentId'],
    };
}

export function PaymentIntentResponseToJSON(json: any): PaymentIntentResponse {
    return PaymentIntentResponseToJSONTyped(json, false);
}

export function PaymentIntentResponseToJSONTyped(value?: PaymentIntentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientSecret': value['clientSecret'],
        'intentId': value['intentId'],
    };
}

