/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactStatusEnum } from './ContactStatusEnum';
import {
    ContactStatusEnumFromJSON,
    ContactStatusEnumFromJSONTyped,
    ContactStatusEnumToJSON,
    ContactStatusEnumToJSONTyped,
} from './ContactStatusEnum';

/**
 * 
 * @export
 * @interface Salon
 */
export interface Salon {
    /**
     * 
     * @type {number}
     * @memberof Salon
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Salon
     */
    name: string;
    /**
     * e.g., City, State or Neighborhood
     * @type {string}
     * @memberof Salon
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof Salon
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Salon
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Salon
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Salon
     */
    description?: string | null;
    /**
     * List of services, e.g., ['Manicure - $30', 'Pedicure - $45']
     * @type {any}
     * @memberof Salon
     */
    services?: any | null;
    /**
     * e.g., Mon-Fri: 9am-7pm\nSat: 10am-5pm
     * @type {string}
     * @memberof Salon
     */
    openingHours?: string | null;
    /**
     * Unique URL-friendly identifier (leave blank to auto-generate)
     * @type {string}
     * @memberof Salon
     */
    sampleUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Salon
     */
    readonly claimed: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Salon
     */
    readonly claimedAt: Date | null;
    /**
     * 
     * @type {ContactStatusEnum}
     * @memberof Salon
     */
    contactStatus?: ContactStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Salon
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Salon
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof Salon
     */
    readonly owner: number | null;
    /**
     * 
     * @type {number}
     * @memberof Salon
     */
    template?: number | null;
}



/**
 * Check if a given object implements the Salon interface.
 */
export function instanceOfSalon(value: object): value is Salon {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('claimed' in value) || value['claimed'] === undefined) return false;
    if (!('claimedAt' in value) || value['claimedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    return true;
}

export function SalonFromJSON(json: any): Salon {
    return SalonFromJSONTyped(json, false);
}

export function SalonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Salon {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'location': json['location'],
        'address': json['address'] == null ? undefined : json['address'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'email': json['email'] == null ? undefined : json['email'],
        'description': json['description'] == null ? undefined : json['description'],
        'services': json['services'] == null ? undefined : json['services'],
        'openingHours': json['opening_hours'] == null ? undefined : json['opening_hours'],
        'sampleUrl': json['sample_url'] == null ? undefined : json['sample_url'],
        'claimed': json['claimed'],
        'claimedAt': (json['claimed_at'] == null ? null : new Date(json['claimed_at'])),
        'contactStatus': json['contact_status'] == null ? undefined : ContactStatusEnumFromJSON(json['contact_status']),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'owner': json['owner'],
        'template': json['template'] == null ? undefined : json['template'],
    };
}

export function SalonToJSON(json: any): Salon {
    return SalonToJSONTyped(json, false);
}

export function SalonToJSONTyped(value?: Omit<Salon, 'id'|'claimed'|'claimed_at'|'created_at'|'updated_at'|'owner'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'location': value['location'],
        'address': value['address'],
        'phone_number': value['phoneNumber'],
        'email': value['email'],
        'description': value['description'],
        'services': value['services'],
        'opening_hours': value['openingHours'],
        'sample_url': value['sampleUrl'],
        'contact_status': ContactStatusEnumToJSON(value['contactStatus']),
        'template': value['template'],
    };
}

