/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Stats
 */
export interface Stats {
    /**
     * 
     * @type {number}
     * @memberof Stats
     */
    totalSalons?: number;
    /**
     * Count of unclaimed salons
     * @type {number}
     * @memberof Stats
     */
    sampleSites?: number;
    /**
     * 
     * @type {number}
     * @memberof Stats
     */
    activeSubscriptions?: number;
    /**
     * Salons with 'notContacted' status
     * @type {number}
     * @memberof Stats
     */
    pendingContacts?: number;
    /**
     * 
     * @type {Date}
     * @memberof Stats
     */
    readonly lastUpdated: Date;
}

/**
 * Check if a given object implements the Stats interface.
 */
export function instanceOfStats(value: object): value is Stats {
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    return true;
}

export function StatsFromJSON(json: any): Stats {
    return StatsFromJSONTyped(json, false);
}

export function StatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stats {
    if (json == null) {
        return json;
    }
    return {
        
        'totalSalons': json['total_salons'] == null ? undefined : json['total_salons'],
        'sampleSites': json['sample_sites'] == null ? undefined : json['sample_sites'],
        'activeSubscriptions': json['active_subscriptions'] == null ? undefined : json['active_subscriptions'],
        'pendingContacts': json['pending_contacts'] == null ? undefined : json['pending_contacts'],
        'lastUpdated': (new Date(json['last_updated'])),
    };
}

export function StatsToJSON(json: any): Stats {
    return StatsToJSONTyped(json, false);
}

export function StatsToJSONTyped(value?: Omit<Stats, 'last_updated'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_salons': value['totalSalons'],
        'sample_sites': value['sampleSites'],
        'active_subscriptions': value['activeSubscriptions'],
        'pending_contacts': value['pendingContacts'],
    };
}

