/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionPlan
 */
export interface SubscriptionPlan {
    /**
     * 
     * @type {number}
     * @memberof SubscriptionPlan
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPlan
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPlan
     */
    description?: string;
    /**
     * Price in cents (e.g., 7900 for $79.00)
     * @type {number}
     * @memberof SubscriptionPlan
     */
    priceCents: number;
    /**
     * Calculates and returns the formatted price string.
     * @type {string}
     * @memberof SubscriptionPlan
     */
    readonly displayPrice: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPlan
     */
    currency?: string;
    /**
     * List of features included in the plan
     * @type {any}
     * @memberof SubscriptionPlan
     */
    features?: any | null;
    /**
     * Stripe Price ID (e.g., price_xxxxxxxxxxxx)
     * @type {string}
     * @memberof SubscriptionPlan
     */
    stripePriceId: string;
    /**
     * Number of trial days (0 for no trial)
     * @type {number}
     * @memberof SubscriptionPlan
     */
    trialPeriodDays?: number;
    /**
     * Whether this plan is available for new subscriptions
     * @type {boolean}
     * @memberof SubscriptionPlan
     */
    readonly isActive: boolean;
    /**
     * Mark as popular for highlighting in UI
     * @type {boolean}
     * @memberof SubscriptionPlan
     */
    isPopular?: boolean;
}

/**
 * Check if a given object implements the SubscriptionPlan interface.
 */
export function instanceOfSubscriptionPlan(value: object): value is SubscriptionPlan {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('priceCents' in value) || value['priceCents'] === undefined) return false;
    if (!('displayPrice' in value) || value['displayPrice'] === undefined) return false;
    if (!('stripePriceId' in value) || value['stripePriceId'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function SubscriptionPlanFromJSON(json: any): SubscriptionPlan {
    return SubscriptionPlanFromJSONTyped(json, false);
}

export function SubscriptionPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPlan {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'priceCents': json['price_cents'],
        'displayPrice': json['display_price'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'features': json['features'] == null ? undefined : json['features'],
        'stripePriceId': json['stripe_price_id'],
        'trialPeriodDays': json['trial_period_days'] == null ? undefined : json['trial_period_days'],
        'isActive': json['is_active'],
        'isPopular': json['is_popular'] == null ? undefined : json['is_popular'],
    };
}

export function SubscriptionPlanToJSON(json: any): SubscriptionPlan {
    return SubscriptionPlanToJSONTyped(json, false);
}

export function SubscriptionPlanToJSONTyped(value?: Omit<SubscriptionPlan, 'id'|'display_price'|'is_active'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'price_cents': value['priceCents'],
        'currency': value['currency'],
        'features': value['features'],
        'stripe_price_id': value['stripePriceId'],
        'trial_period_days': value['trialPeriodDays'],
        'is_popular': value['isPopular'],
    };
}

