/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionResponse
 */
export interface SubscriptionResponse {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    subscriptionId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    clientSecret?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the SubscriptionResponse interface.
 */
export function instanceOfSubscriptionResponse(value: object): value is SubscriptionResponse {
    if (!('subscriptionId' in value) || value['subscriptionId'] === undefined) return false;
    return true;
}

export function SubscriptionResponseFromJSON(json: any): SubscriptionResponse {
    return SubscriptionResponseFromJSONTyped(json, false);
}

export function SubscriptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'subscriptionId': json['subscriptionId'],
        'clientSecret': json['clientSecret'] == null ? undefined : json['clientSecret'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function SubscriptionResponseToJSON(json: any): SubscriptionResponse {
    return SubscriptionResponseToJSONTyped(json, false);
}

export function SubscriptionResponseToJSONTyped(value?: SubscriptionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscriptionId': value['subscriptionId'],
        'clientSecret': value['clientSecret'],
        'message': value['message'],
    };
}

