/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Template
 */
export interface Template {
    /**
     * 
     * @type {number}
     * @memberof Template
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    previewImageUrl?: string | null;
    /**
     * 
     * @type {any}
     * @memberof Template
     */
    features?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof Template
     */
    isMobileOptimized?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Template
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Template
     */
    readonly updatedAt: Date;
}

/**
 * Check if a given object implements the Template interface.
 */
export function instanceOfTemplate(value: object): value is Template {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TemplateFromJSON(json: any): Template {
    return TemplateFromJSONTyped(json, false);
}

export function TemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Template {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'previewImageUrl': json['preview_image_url'] == null ? undefined : json['preview_image_url'],
        'features': json['features'] == null ? undefined : json['features'],
        'isMobileOptimized': json['is_mobile_optimized'] == null ? undefined : json['is_mobile_optimized'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function TemplateToJSON(json: any): Template {
    return TemplateToJSONTyped(json, false);
}

export function TemplateToJSONTyped(value?: Omit<Template, 'id'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'preview_image_url': value['previewImageUrl'],
        'features': value['features'],
        'is_mobile_optimized': value['isMobileOptimized'],
    };
}

