/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileUpdate
 */
export interface UserProfileUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdate
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdate
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdate
     */
    phoneNumber?: string | null;
}

/**
 * Check if a given object implements the UserProfileUpdate interface.
 */
export function instanceOfUserProfileUpdate(value: object): value is UserProfileUpdate {
    return true;
}

export function UserProfileUpdateFromJSON(json: any): UserProfileUpdate {
    return UserProfileUpdateFromJSONTyped(json, false);
}

export function UserProfileUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
    };
}

export function UserProfileUpdateToJSON(json: any): UserProfileUpdate {
    return UserProfileUpdateToJSONTyped(json, false);
}

export function UserProfileUpdateToJSONTyped(value?: UserProfileUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'phone_number': value['phoneNumber'],
    };
}

