/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookResponse
 */
export interface WebhookResponse {
    /**
     * 
     * @type {boolean}
     * @memberof WebhookResponse
     */
    received: boolean;
}

/**
 * Check if a given object implements the WebhookResponse interface.
 */
export function instanceOfWebhookResponse(value: object): value is WebhookResponse {
    if (!('received' in value) || value['received'] === undefined) return false;
    return true;
}

export function WebhookResponseFromJSON(json: any): WebhookResponse {
    return WebhookResponseFromJSONTyped(json, false);
}

export function WebhookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'received': json['received'],
    };
}

export function WebhookResponseToJSON(json: any): WebhookResponse {
    return WebhookResponseToJSONTyped(json, false);
}

export function WebhookResponseToJSONTyped(value?: WebhookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'received': value['received'],
    };
}

