sudo nano /etc/nginx/sites-available/1panel.pussco.com 


sudo certbot --nginx -d 1panel.pussco.com


server {
    listen 80;
    server_name 1panel.pussco.com; # Change to your domain
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 1panel.pussco.com;

    # SSL Configuration - Get certificates first with:
    # sudo certbot --nginx -d 1panel.pussco.com
    ssl_certificate /etc/letsencrypt/live/1panel.pussco.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/1panel.pussco.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:12345; # Note the correct port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_read_timeout 300s;
    }

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
}


sudo ln -s /etc/nginx/sites-available/1panel.pussco.com /etc/nginx/sites-enabled/
sudo nginx -t && sudo systemctl restart nginx