# Generated by Django 5.2 on 2025-05-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
