/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BlogComment,
  BlogPost,
  ChangePassword,
  PaginatedBlogPostListList,
  PaginatedSalonList,
  PaginatedSubscriptionPlanList,
  PaginatedTemplateList,
  PatchedBlogPost,
  PatchedChangePassword,
  PatchedSalon,
  PatchedUserProfileUpdate,
  PaymentIntentRequest,
  PaymentIntentResponse,
  Register,
  Salon,
  Stats,
  SubscriptionPlan,
  SubscriptionRequest,
  SubscriptionResponse,
  Template,
  TokenObtainPair,
  TokenRefresh,
  TokenVerify,
  User,
  UserProfileUpdate,
} from '../models/index';
import {
    BlogCommentFromJSON,
    BlogCommentToJSON,
    BlogPostFromJSON,
    BlogPostToJSON,
    ChangePasswordFromJSON,
    ChangePasswordToJSON,
    PaginatedBlogPostListListFromJSON,
    PaginatedBlogPostListListToJSON,
    PaginatedSalonListFromJSON,
    PaginatedSalonListToJSON,
    PaginatedSubscriptionPlanListFromJSON,
    PaginatedSubscriptionPlanListToJSON,
    PaginatedTemplateListFromJSON,
    PaginatedTemplateListToJSON,
    PatchedBlogPostFromJSON,
    PatchedBlogPostToJSON,
    PatchedChangePasswordFromJSON,
    PatchedChangePasswordToJSON,
    PatchedSalonFromJSON,
    PatchedSalonToJSON,
    PatchedUserProfileUpdateFromJSON,
    PatchedUserProfileUpdateToJSON,
    PaymentIntentRequestFromJSON,
    PaymentIntentRequestToJSON,
    PaymentIntentResponseFromJSON,
    PaymentIntentResponseToJSON,
    RegisterFromJSON,
    RegisterToJSON,
    SalonFromJSON,
    SalonToJSON,
    StatsFromJSON,
    StatsToJSON,
    SubscriptionPlanFromJSON,
    SubscriptionPlanToJSON,
    SubscriptionRequestFromJSON,
    SubscriptionRequestToJSON,
    SubscriptionResponseFromJSON,
    SubscriptionResponseToJSON,
    TemplateFromJSON,
    TemplateToJSON,
    TokenObtainPairFromJSON,
    TokenObtainPairToJSON,
    TokenRefreshFromJSON,
    TokenRefreshToJSON,
    TokenVerifyFromJSON,
    TokenVerifyToJSON,
    UserFromJSON,
    UserToJSON,
    UserProfileUpdateFromJSON,
    UserProfileUpdateToJSON,
} from '../models/index';

export interface ApiAuthChangePasswordPartialUpdateRequest {
    patchedChangePassword?: PatchedChangePassword;
}

export interface ApiAuthChangePasswordUpdateRequest {
    changePassword: ChangePassword;
}

export interface ApiAuthProfilePartialUpdateRequest {
    patchedUserProfileUpdate?: PatchedUserProfileUpdate;
}

export interface ApiAuthProfileUpdateRequest {
    userProfileUpdate?: UserProfileUpdate;
}

export interface ApiAuthRegisterCreateRequest {
    register: Register;
}

export interface ApiAuthTokenCreateRequest {
    tokenObtainPair: Omit<TokenObtainPair, 'access'|'refresh'>;
}

export interface ApiAuthTokenRefreshCreateRequest {
    tokenRefresh: Omit<TokenRefresh, 'access'>;
}

export interface ApiAuthTokenVerifyCreateRequest {
    tokenVerify: TokenVerify;
}

export interface ApiBlogCommentsApproveCreateRequest {
    id: number;
    blogComment: Omit<BlogComment, 'id'|'user'|'approved'|'created_at'>;
}

export interface ApiBlogCommentsDestroyRequest {
    id: number;
}

export interface ApiBlogPostsCommentsCreateRequest {
    slug: string;
    blogPost: Omit<BlogPost, 'id'|'slug'|'author'|'view_count'|'created_at'|'updated_at'|'comments'>;
}

export interface ApiBlogPostsCommentsRetrieveRequest {
    slug: string;
}

export interface ApiBlogPostsCreateRequest {
    blogPost: Omit<BlogPost, 'id'|'slug'|'author'|'view_count'|'created_at'|'updated_at'|'comments'>;
}

export interface ApiBlogPostsDestroyRequest {
    slug: string;
}

export interface ApiBlogPostsListRequest {
    limit?: number;
    offset?: number;
}

export interface ApiBlogPostsPartialUpdateRequest {
    slug: string;
    patchedBlogPost?: Omit<PatchedBlogPost, 'id'|'slug'|'author'|'view_count'|'created_at'|'updated_at'|'comments'>;
}

export interface ApiBlogPostsRetrieveRequest {
    slug: string;
}

export interface ApiBlogPostsUpdateRequest {
    slug: string;
    blogPost: Omit<BlogPost, 'id'|'slug'|'author'|'view_count'|'created_at'|'updated_at'|'comments'>;
}

export interface ApiPaymentsCreateIntentCreateRequest {
    paymentIntentRequest: PaymentIntentRequest;
}

export interface ApiPaymentsCreateSubscriptionCreateRequest {
    subscriptionRequest: SubscriptionRequest;
}

export interface ApiPaymentsPlansListRequest {
    limit?: number;
    offset?: number;
}

export interface ApiPaymentsPlansRetrieveRequest {
    id: number;
}

export interface ApiSalonsClaimCreateRequest {
    id: number;
    salon: Omit<Salon, 'id'|'claimed'|'claimed_at'|'created_at'|'updated_at'|'owner'>;
}

export interface ApiSalonsContactLeadsCreateRequest {
    salon: Omit<Salon, 'id'|'claimed'|'claimed_at'|'created_at'|'updated_at'|'owner'>;
}

export interface ApiSalonsCreateRequest {
    salon: Omit<Salon, 'id'|'claimed'|'claimed_at'|'created_at'|'updated_at'|'owner'>;
}

export interface ApiSalonsDestroyRequest {
    id: number;
}

export interface ApiSalonsListRequest {
    limit?: number;
    offset?: number;
}

export interface ApiSalonsPartialUpdateRequest {
    id: number;
    patchedSalon?: Omit<PatchedSalon, 'id'|'claimed'|'claimed_at'|'created_at'|'updated_at'|'owner'>;
}

export interface ApiSalonsRetrieveRequest {
    id: number;
}

export interface ApiSalonsSampleRetrieveRequest {
    sampleUrl: string;
}

export interface ApiSalonsUpdateRequest {
    id: number;
    salon: Omit<Salon, 'id'|'claimed'|'claimed_at'|'created_at'|'updated_at'|'owner'>;
}

export interface ApiTemplatesListRequest {
    limit?: number;
    offset?: number;
}

export interface ApiTemplatesRetrieveRequest {
    id: number;
}

/**
 * 
 */
export class ApiApi extends runtime.BaseAPI {

    /**
     * Changes the password for the currently authenticated user (using JWT).
     * Change User Password (Partial - not typical)
     */
    async apiAuthChangePasswordPartialUpdateRaw(requestParameters: ApiAuthChangePasswordPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChangePassword>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auth/change-password/`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedChangePasswordToJSON(requestParameters['patchedChangePassword']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChangePasswordFromJSON(jsonValue));
    }

    /**
     * Changes the password for the currently authenticated user (using JWT).
     * Change User Password (Partial - not typical)
     */
    async apiAuthChangePasswordPartialUpdate(requestParameters: ApiAuthChangePasswordPartialUpdateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChangePassword> {
        const response = await this.apiAuthChangePasswordPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Changes the password for the currently authenticated user (using JWT).
     * Change User Password
     */
    async apiAuthChangePasswordUpdateRaw(requestParameters: ApiAuthChangePasswordUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChangePassword>> {
        if (requestParameters['changePassword'] == null) {
            throw new runtime.RequiredError(
                'changePassword',
                'Required parameter "changePassword" was null or undefined when calling apiAuthChangePasswordUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auth/change-password/`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChangePasswordToJSON(requestParameters['changePassword']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChangePasswordFromJSON(jsonValue));
    }

    /**
     * Changes the password for the currently authenticated user (using JWT).
     * Change User Password
     */
    async apiAuthChangePasswordUpdate(requestParameters: ApiAuthChangePasswordUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChangePassword> {
        const response = await this.apiAuthChangePasswordUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets or updates the profile of the currently authenticated user (using JWT).
     * Update User Profile (Partial)
     */
    async apiAuthProfilePartialUpdateRaw(requestParameters: ApiAuthProfilePartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileUpdate>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auth/profile/`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedUserProfileUpdateToJSON(requestParameters['patchedUserProfileUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProfileUpdateFromJSON(jsonValue));
    }

    /**
     * Gets or updates the profile of the currently authenticated user (using JWT).
     * Update User Profile (Partial)
     */
    async apiAuthProfilePartialUpdate(requestParameters: ApiAuthProfilePartialUpdateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileUpdate> {
        const response = await this.apiAuthProfilePartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets or updates the profile of the currently authenticated user (using JWT).
     * Retrieve User Profile
     */
    async apiAuthProfileRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auth/profile/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Gets or updates the profile of the currently authenticated user (using JWT).
     * Retrieve User Profile
     */
    async apiAuthProfileRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.apiAuthProfileRetrieveRaw(initOverrides);
        return await response.value();
    }

    /**
     * Gets or updates the profile of the currently authenticated user (using JWT).
     * Update User Profile (Full)
     */
    async apiAuthProfileUpdateRaw(requestParameters: ApiAuthProfileUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileUpdate>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auth/profile/`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserProfileUpdateToJSON(requestParameters['userProfileUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProfileUpdateFromJSON(jsonValue));
    }

    /**
     * Gets or updates the profile of the currently authenticated user (using JWT).
     * Update User Profile (Full)
     */
    async apiAuthProfileUpdate(requestParameters: ApiAuthProfileUpdateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileUpdate> {
        const response = await this.apiAuthProfileUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Registers a new user.
     * User Registration
     */
    async apiAuthRegisterCreateRaw(requestParameters: ApiAuthRegisterCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Register>> {
        if (requestParameters['register'] == null) {
            throw new runtime.RequiredError(
                'register',
                'Required parameter "register" was null or undefined when calling apiAuthRegisterCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/auth/register/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterToJSON(requestParameters['register']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterFromJSON(jsonValue));
    }

    /**
     * Registers a new user.
     * User Registration
     */
    async apiAuthRegisterCreate(requestParameters: ApiAuthRegisterCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Register> {
        const response = await this.apiAuthRegisterCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Takes a set of user credentials and returns an access and refresh JSON web token pair to prove the authentication of those credentials.
     */
    async apiAuthTokenCreateRaw(requestParameters: ApiAuthTokenCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenObtainPair>> {
        if (requestParameters['tokenObtainPair'] == null) {
            throw new runtime.RequiredError(
                'tokenObtainPair',
                'Required parameter "tokenObtainPair" was null or undefined when calling apiAuthTokenCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/auth/token/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenObtainPairToJSON(requestParameters['tokenObtainPair']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenObtainPairFromJSON(jsonValue));
    }

    /**
     * Takes a set of user credentials and returns an access and refresh JSON web token pair to prove the authentication of those credentials.
     */
    async apiAuthTokenCreate(requestParameters: ApiAuthTokenCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenObtainPair> {
        const response = await this.apiAuthTokenCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Takes a refresh type JSON web token and returns an access type JSON web token if the refresh token is valid.
     */
    async apiAuthTokenRefreshCreateRaw(requestParameters: ApiAuthTokenRefreshCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenRefresh>> {
        if (requestParameters['tokenRefresh'] == null) {
            throw new runtime.RequiredError(
                'tokenRefresh',
                'Required parameter "tokenRefresh" was null or undefined when calling apiAuthTokenRefreshCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/auth/token/refresh/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenRefreshToJSON(requestParameters['tokenRefresh']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenRefreshFromJSON(jsonValue));
    }

    /**
     * Takes a refresh type JSON web token and returns an access type JSON web token if the refresh token is valid.
     */
    async apiAuthTokenRefreshCreate(requestParameters: ApiAuthTokenRefreshCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenRefresh> {
        const response = await this.apiAuthTokenRefreshCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Takes a token and indicates if it is valid.  This view provides no information about a token\'s fitness for a particular use.
     */
    async apiAuthTokenVerifyCreateRaw(requestParameters: ApiAuthTokenVerifyCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenVerify>> {
        if (requestParameters['tokenVerify'] == null) {
            throw new runtime.RequiredError(
                'tokenVerify',
                'Required parameter "tokenVerify" was null or undefined when calling apiAuthTokenVerifyCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/auth/token/verify/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenVerifyToJSON(requestParameters['tokenVerify']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenVerifyFromJSON(jsonValue));
    }

    /**
     * Takes a token and indicates if it is valid.  This view provides no information about a token\'s fitness for a particular use.
     */
    async apiAuthTokenVerifyCreate(requestParameters: ApiAuthTokenVerifyCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenVerify> {
        const response = await this.apiAuthTokenVerifyCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint for moderation actions on comments (approve, delete). Accessed via /api/blog/comments/{comment_pk}/action/ Requires Admin permissions.
     */
    async apiBlogCommentsApproveCreateRaw(requestParameters: ApiBlogCommentsApproveCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlogComment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiBlogCommentsApproveCreate().'
            );
        }

        if (requestParameters['blogComment'] == null) {
            throw new runtime.RequiredError(
                'blogComment',
                'Required parameter "blogComment" was null or undefined when calling apiBlogCommentsApproveCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/blog/comments/{id}/approve/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BlogCommentToJSON(requestParameters['blogComment']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlogCommentFromJSON(jsonValue));
    }

    /**
     * API endpoint for moderation actions on comments (approve, delete). Accessed via /api/blog/comments/{comment_pk}/action/ Requires Admin permissions.
     */
    async apiBlogCommentsApproveCreate(requestParameters: ApiBlogCommentsApproveCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlogComment> {
        const response = await this.apiBlogCommentsApproveCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a blog comment.
     */
    async apiBlogCommentsDestroyRaw(requestParameters: ApiBlogCommentsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiBlogCommentsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/blog/comments/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a blog comment.
     */
    async apiBlogCommentsDestroy(requestParameters: ApiBlogCommentsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiBlogCommentsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates a new comment on a specific blog post.
     */
    async apiBlogPostsCommentsCreateRaw(requestParameters: ApiBlogPostsCommentsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlogPost>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling apiBlogPostsCommentsCreate().'
            );
        }

        if (requestParameters['blogPost'] == null) {
            throw new runtime.RequiredError(
                'blogPost',
                'Required parameter "blogPost" was null or undefined when calling apiBlogPostsCommentsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/blog/posts/{slug}/comments/`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BlogPostToJSON(requestParameters['blogPost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlogPostFromJSON(jsonValue));
    }

    /**
     * Creates a new comment on a specific blog post.
     */
    async apiBlogPostsCommentsCreate(requestParameters: ApiBlogPostsCommentsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlogPost> {
        const response = await this.apiBlogPostsCommentsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists comments for a specific blog post.
     */
    async apiBlogPostsCommentsRetrieveRaw(requestParameters: ApiBlogPostsCommentsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlogPost>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling apiBlogPostsCommentsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/blog/posts/{slug}/comments/`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlogPostFromJSON(jsonValue));
    }

    /**
     * Lists comments for a specific blog post.
     */
    async apiBlogPostsCommentsRetrieve(requestParameters: ApiBlogPostsCommentsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlogPost> {
        const response = await this.apiBlogPostsCommentsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint for Blog Posts. Supports CRUD, filtering, and comment management. Uses slug for detail lookups.
     */
    async apiBlogPostsCreateRaw(requestParameters: ApiBlogPostsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlogPost>> {
        if (requestParameters['blogPost'] == null) {
            throw new runtime.RequiredError(
                'blogPost',
                'Required parameter "blogPost" was null or undefined when calling apiBlogPostsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/blog/posts/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BlogPostToJSON(requestParameters['blogPost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlogPostFromJSON(jsonValue));
    }

    /**
     * API endpoint for Blog Posts. Supports CRUD, filtering, and comment management. Uses slug for detail lookups.
     */
    async apiBlogPostsCreate(requestParameters: ApiBlogPostsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlogPost> {
        const response = await this.apiBlogPostsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint for Blog Posts. Supports CRUD, filtering, and comment management. Uses slug for detail lookups.
     */
    async apiBlogPostsDestroyRaw(requestParameters: ApiBlogPostsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling apiBlogPostsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/blog/posts/{slug}/`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * API endpoint for Blog Posts. Supports CRUD, filtering, and comment management. Uses slug for detail lookups.
     */
    async apiBlogPostsDestroy(requestParameters: ApiBlogPostsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiBlogPostsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * API endpoint for Blog Posts. Supports CRUD, filtering, and comment management. Uses slug for detail lookups.
     */
    async apiBlogPostsListRaw(requestParameters: ApiBlogPostsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedBlogPostListList>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/blog/posts/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedBlogPostListListFromJSON(jsonValue));
    }

    /**
     * API endpoint for Blog Posts. Supports CRUD, filtering, and comment management. Uses slug for detail lookups.
     */
    async apiBlogPostsList(requestParameters: ApiBlogPostsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedBlogPostListList> {
        const response = await this.apiBlogPostsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint for Blog Posts. Supports CRUD, filtering, and comment management. Uses slug for detail lookups.
     */
    async apiBlogPostsPartialUpdateRaw(requestParameters: ApiBlogPostsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlogPost>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling apiBlogPostsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/blog/posts/{slug}/`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedBlogPostToJSON(requestParameters['patchedBlogPost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlogPostFromJSON(jsonValue));
    }

    /**
     * API endpoint for Blog Posts. Supports CRUD, filtering, and comment management. Uses slug for detail lookups.
     */
    async apiBlogPostsPartialUpdate(requestParameters: ApiBlogPostsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlogPost> {
        const response = await this.apiBlogPostsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Override retrieve to increment view count.
     */
    async apiBlogPostsRetrieveRaw(requestParameters: ApiBlogPostsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlogPost>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling apiBlogPostsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/blog/posts/{slug}/`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlogPostFromJSON(jsonValue));
    }

    /**
     * Override retrieve to increment view count.
     */
    async apiBlogPostsRetrieve(requestParameters: ApiBlogPostsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlogPost> {
        const response = await this.apiBlogPostsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint for Blog Posts. Supports CRUD, filtering, and comment management. Uses slug for detail lookups.
     */
    async apiBlogPostsUpdateRaw(requestParameters: ApiBlogPostsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlogPost>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling apiBlogPostsUpdate().'
            );
        }

        if (requestParameters['blogPost'] == null) {
            throw new runtime.RequiredError(
                'blogPost',
                'Required parameter "blogPost" was null or undefined when calling apiBlogPostsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/blog/posts/{slug}/`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BlogPostToJSON(requestParameters['blogPost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlogPostFromJSON(jsonValue));
    }

    /**
     * API endpoint for Blog Posts. Supports CRUD, filtering, and comment management. Uses slug for detail lookups.
     */
    async apiBlogPostsUpdate(requestParameters: ApiBlogPostsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlogPost> {
        const response = await this.apiBlogPostsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint to retrieve the site-wide statistics. Requires admin privileges.
     */
    async apiCoreStatsRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Stats>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/core/stats/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatsFromJSON(jsonValue));
    }

    /**
     * API endpoint to retrieve the site-wide statistics. Requires admin privileges.
     */
    async apiCoreStatsRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Stats> {
        const response = await this.apiCoreStatsRetrieveRaw(initOverrides);
        return await response.value();
    }

    /**
     * Initializes a Stripe Payment Intent for a one-time payment.
     * Create Payment Intent
     */
    async apiPaymentsCreateIntentCreateRaw(requestParameters: ApiPaymentsCreateIntentCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentIntentResponse>> {
        if (requestParameters['paymentIntentRequest'] == null) {
            throw new runtime.RequiredError(
                'paymentIntentRequest',
                'Required parameter "paymentIntentRequest" was null or undefined when calling apiPaymentsCreateIntentCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/payments/create-intent/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentIntentRequestToJSON(requestParameters['paymentIntentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentIntentResponseFromJSON(jsonValue));
    }

    /**
     * Initializes a Stripe Payment Intent for a one-time payment.
     * Create Payment Intent
     */
    async apiPaymentsCreateIntentCreate(requestParameters: ApiPaymentsCreateIntentCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentIntentResponse> {
        const response = await this.apiPaymentsCreateIntentCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Initiates a Stripe subscription for the selected plan.
     * Create Subscription
     */
    async apiPaymentsCreateSubscriptionCreateRaw(requestParameters: ApiPaymentsCreateSubscriptionCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionResponse>> {
        if (requestParameters['subscriptionRequest'] == null) {
            throw new runtime.RequiredError(
                'subscriptionRequest',
                'Required parameter "subscriptionRequest" was null or undefined when calling apiPaymentsCreateSubscriptionCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/payments/create-subscription/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubscriptionRequestToJSON(requestParameters['subscriptionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionResponseFromJSON(jsonValue));
    }

    /**
     * Initiates a Stripe subscription for the selected plan.
     * Create Subscription
     */
    async apiPaymentsCreateSubscriptionCreate(requestParameters: ApiPaymentsCreateSubscriptionCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionResponse> {
        const response = await this.apiPaymentsCreateSubscriptionCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPaymentsPlansListRaw(requestParameters: ApiPaymentsPlansListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSubscriptionPlanList>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/payments/plans/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedSubscriptionPlanListFromJSON(jsonValue));
    }

    /**
     */
    async apiPaymentsPlansList(requestParameters: ApiPaymentsPlansListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSubscriptionPlanList> {
        const response = await this.apiPaymentsPlansListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPaymentsPlansRetrieveRaw(requestParameters: ApiPaymentsPlansRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionPlan>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPaymentsPlansRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/payments/plans/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionPlanFromJSON(jsonValue));
    }

    /**
     */
    async apiPaymentsPlansRetrieve(requestParameters: ApiPaymentsPlansRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionPlan> {
        const response = await this.apiPaymentsPlansRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allows an authenticated user to claim an unclaimed salon. Updates ownership and statistics.
     */
    async apiSalonsClaimCreateRaw(requestParameters: ApiSalonsClaimCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Salon>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSalonsClaimCreate().'
            );
        }

        if (requestParameters['salon'] == null) {
            throw new runtime.RequiredError(
                'salon',
                'Required parameter "salon" was null or undefined when calling apiSalonsClaimCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/salons/{id}/claim/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SalonToJSON(requestParameters['salon']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SalonFromJSON(jsonValue));
    }

    /**
     * Allows an authenticated user to claim an unclaimed salon. Updates ownership and statistics.
     */
    async apiSalonsClaimCreate(requestParameters: ApiSalonsClaimCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Salon> {
        const response = await this.apiSalonsClaimCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Admin action to mark multiple salons (by ID) as having been contacted. Updates contact_status and recalculates pending contacts statistics. Expects JSON: {\"leadIds\": [1, 2, ...]}
     */
    async apiSalonsContactLeadsCreateRaw(requestParameters: ApiSalonsContactLeadsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Salon>> {
        if (requestParameters['salon'] == null) {
            throw new runtime.RequiredError(
                'salon',
                'Required parameter "salon" was null or undefined when calling apiSalonsContactLeadsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/salons/contact-leads/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SalonToJSON(requestParameters['salon']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SalonFromJSON(jsonValue));
    }

    /**
     * Admin action to mark multiple salons (by ID) as having been contacted. Updates contact_status and recalculates pending contacts statistics. Expects JSON: {\"leadIds\": [1, 2, ...]}
     */
    async apiSalonsContactLeadsCreate(requestParameters: ApiSalonsContactLeadsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Salon> {
        const response = await this.apiSalonsContactLeadsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint for Salons. Handles CRUD, retrieving by sample_url, claiming, and marking leads as contacted. Permissions vary by action.
     */
    async apiSalonsCreateRaw(requestParameters: ApiSalonsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Salon>> {
        if (requestParameters['salon'] == null) {
            throw new runtime.RequiredError(
                'salon',
                'Required parameter "salon" was null or undefined when calling apiSalonsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/salons/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SalonToJSON(requestParameters['salon']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SalonFromJSON(jsonValue));
    }

    /**
     * API endpoint for Salons. Handles CRUD, retrieving by sample_url, claiming, and marking leads as contacted. Permissions vary by action.
     */
    async apiSalonsCreate(requestParameters: ApiSalonsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Salon> {
        const response = await this.apiSalonsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint for Salons. Handles CRUD, retrieving by sample_url, claiming, and marking leads as contacted. Permissions vary by action.
     */
    async apiSalonsDestroyRaw(requestParameters: ApiSalonsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSalonsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/salons/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * API endpoint for Salons. Handles CRUD, retrieving by sample_url, claiming, and marking leads as contacted. Permissions vary by action.
     */
    async apiSalonsDestroy(requestParameters: ApiSalonsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiSalonsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * API endpoint for Salons. Handles CRUD, retrieving by sample_url, claiming, and marking leads as contacted. Permissions vary by action.
     */
    async apiSalonsListRaw(requestParameters: ApiSalonsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSalonList>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/salons/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedSalonListFromJSON(jsonValue));
    }

    /**
     * API endpoint for Salons. Handles CRUD, retrieving by sample_url, claiming, and marking leads as contacted. Permissions vary by action.
     */
    async apiSalonsList(requestParameters: ApiSalonsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSalonList> {
        const response = await this.apiSalonsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint for Salons. Handles CRUD, retrieving by sample_url, claiming, and marking leads as contacted. Permissions vary by action.
     */
    async apiSalonsPartialUpdateRaw(requestParameters: ApiSalonsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Salon>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSalonsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/salons/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedSalonToJSON(requestParameters['patchedSalon']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SalonFromJSON(jsonValue));
    }

    /**
     * API endpoint for Salons. Handles CRUD, retrieving by sample_url, claiming, and marking leads as contacted. Permissions vary by action.
     */
    async apiSalonsPartialUpdate(requestParameters: ApiSalonsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Salon> {
        const response = await this.apiSalonsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint for Salons. Handles CRUD, retrieving by sample_url, claiming, and marking leads as contacted. Permissions vary by action.
     */
    async apiSalonsRetrieveRaw(requestParameters: ApiSalonsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Salon>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSalonsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/salons/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SalonFromJSON(jsonValue));
    }

    /**
     * API endpoint for Salons. Handles CRUD, retrieving by sample_url, claiming, and marking leads as contacted. Permissions vary by action.
     */
    async apiSalonsRetrieve(requestParameters: ApiSalonsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Salon> {
        const response = await this.apiSalonsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a single salon instance using its unique \'sample_url\'.
     */
    async apiSalonsSampleRetrieveRaw(requestParameters: ApiSalonsSampleRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Salon>> {
        if (requestParameters['sampleUrl'] == null) {
            throw new runtime.RequiredError(
                'sampleUrl',
                'Required parameter "sampleUrl" was null or undefined when calling apiSalonsSampleRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/salons/sample/{sample_url}/`.replace(`{${"sample_url"}}`, encodeURIComponent(String(requestParameters['sampleUrl']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SalonFromJSON(jsonValue));
    }

    /**
     * Retrieves a single salon instance using its unique \'sample_url\'.
     */
    async apiSalonsSampleRetrieve(requestParameters: ApiSalonsSampleRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Salon> {
        const response = await this.apiSalonsSampleRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint for Salons. Handles CRUD, retrieving by sample_url, claiming, and marking leads as contacted. Permissions vary by action.
     */
    async apiSalonsUpdateRaw(requestParameters: ApiSalonsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Salon>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSalonsUpdate().'
            );
        }

        if (requestParameters['salon'] == null) {
            throw new runtime.RequiredError(
                'salon',
                'Required parameter "salon" was null or undefined when calling apiSalonsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/salons/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SalonToJSON(requestParameters['salon']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SalonFromJSON(jsonValue));
    }

    /**
     * API endpoint for Salons. Handles CRUD, retrieving by sample_url, claiming, and marking leads as contacted. Permissions vary by action.
     */
    async apiSalonsUpdate(requestParameters: ApiSalonsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Salon> {
        const response = await this.apiSalonsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint that allows Templates to be viewed. Read-only.
     */
    async apiTemplatesListRaw(requestParameters: ApiTemplatesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedTemplateList>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/templates/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedTemplateListFromJSON(jsonValue));
    }

    /**
     * API endpoint that allows Templates to be viewed. Read-only.
     */
    async apiTemplatesList(requestParameters: ApiTemplatesListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedTemplateList> {
        const response = await this.apiTemplatesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint that allows Templates to be viewed. Read-only.
     */
    async apiTemplatesRetrieveRaw(requestParameters: ApiTemplatesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Template>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTemplatesRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/templates/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateFromJSON(jsonValue));
    }

    /**
     * API endpoint that allows Templates to be viewed. Read-only.
     */
    async apiTemplatesRetrieve(requestParameters: ApiTemplatesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Template> {
        const response = await this.apiTemplatesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
