/* tslint:disable */
/* eslint-disable */
/**
 * My Salon Project API
 * API documentation for the Salon Site project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebhookResponse,
} from '../models/index';
import {
    WebhookResponseFromJSON,
    WebhookResponseToJSON,
} from '../models/index';

export interface StripeWebhookCreateRequest {
    requestBody?: { [key: string]: any; };
}

/**
 * 
 */
export class StripeApi extends runtime.BaseAPI {

    /**
     * Receives and processes events sent from Stripe.
     * Stripe Webhook Handler
     */
    async stripeWebhookCreateRaw(requestParameters: StripeWebhookCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/stripe/webhook/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookResponseFromJSON(jsonValue));
    }

    /**
     * Receives and processes events sent from Stripe.
     * Stripe Webhook Handler
     */
    async stripeWebhookCreate(requestParameters: StripeWebhookCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookResponse> {
        const response = await this.stripeWebhookCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
