# Generated by Django 5.2 on 2025-05-04 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier (leave blank to auto-generate)', max_length=255, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='A short summary of the post (optional)', null=True)),
                ('cover_image', models.URLField(blank=True, help_text='URL of the main image for the post', max_length=500, null=True)),
                ('category', models.CharField(choices=[('nail_art', 'Nail Art'), ('marketing', 'Marketing'), ('business_advice', 'Business Advice'), ('trends', 'Trends'), ('product_reviews', 'Product Reviews'), ('tutorials', 'Tutorials'), ('other', 'Other')], default='other', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, help_text="List of tags, e.g., ['manicure', 'trends']")),
                ('published', models.BooleanField(default=False, help_text='Check this to make the post visible to the public')),
                ('featured', models.BooleanField(default=False, help_text='Check this to feature the post (e.g., on homepage)')),
                ('published_at', models.DateTimeField(blank=True, help_text='Optional: Set a future date/time to publish', null=True)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('content', models.TextField()),
                ('approved', models.BooleanField(default=False, help_text='Comments must be approved to be publicly visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
