# Generated by Django 5.2 on 2025-05-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('content', models.TextField(verbose_name='Content')),
                ('approved', models.BooleanField(default=False, help_text='Comments must be approved to be publicly visible', verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier (leave blank to auto-generate)', max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('excerpt', models.TextField(blank=True, help_text='A short summary of the post (optional)', null=True, verbose_name='Excerpt')),
                ('cover_image', models.URLField(blank=True, help_text='URL of the main image for the post', max_length=500, null=True, verbose_name='Cover Image')),
                ('category', models.CharField(choices=[('nail_art', 'Nail Art'), ('marketing', 'Marketing'), ('business_advice', 'Business Advice'), ('trends', 'Trends'), ('product_reviews', 'Product Reviews'), ('tutorials', 'Tutorials'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags, e.g., ["manicure", "trends"]', verbose_name='Tags')),
                ('published', models.BooleanField(default=False, help_text='Check this to make the post visible to the public', verbose_name='Published')),
                ('featured', models.BooleanField(default=False, help_text='Check this to feature the post (e.g., on homepage)', verbose_name='Featured')),
                ('published_at', models.DateTimeField(blank=True, help_text='Optional: Set a future date/time to publish', null=True, verbose_name='Published At')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
