# Generated by Django 5.2 on 2025-05-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Salon Name')),
                ('location', models.CharField(help_text='e.g., City, State or Neighborhood', max_length=200, verbose_name='Location')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('image', models.ImageField(blank=True, default='media/default.png', null=True, upload_to='media/', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('services', models.JSONField(blank=True, default=list, help_text='List of services, e.g., [{"name": "Manicure", "price": "$30", "description": "..."}]', verbose_name='Services')),
                ('opening_hours', models.TextField(blank=True, help_text='e.g., Mon-Fri: 9am-7pm\\nSat: 10am-5pm', null=True, verbose_name='Opening Hours')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='salon_logos/', verbose_name='Logo Image')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='salon_covers/', verbose_name='Cover Image')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='salon_about/', verbose_name='About Image')),
                ('footer_logo_image', models.ImageField(blank=True, null=True, upload_to='salon_logos/', verbose_name='Footer Logo Image')),
                ('hero_subtitle', models.CharField(blank=True, help_text='Subtitle displayed below the main title in the hero section', max_length=255, null=True, verbose_name='Hero Subtitle')),
                ('services_tagline', models.CharField(blank=True, help_text='Short description for the services section header', max_length=255, null=True, verbose_name='Services Tagline')),
                ('gallery_tagline', models.CharField(blank=True, help_text='Short description for the gallery section header', max_length=255, null=True, verbose_name='Gallery Tagline')),
                ('footer_about', models.TextField(blank=True, help_text='About text displayed in the footer', null=True, verbose_name='Footer About')),
                ('booking_url', models.URLField(blank=True, help_text='External URL for online booking system', null=True, verbose_name='Booking URL')),
                ('gallery_url', models.URLField(blank=True, help_text='External URL for a full gallery page if not displayed directly', null=True, verbose_name='Gallery URL')),
                ('services_url', models.URLField(blank=True, help_text='External URL for a full services menu page', null=True, verbose_name='Services URL')),
                ('map_embed_url', models.URLField(blank=True, help_text='URL for embedding a map (e.g., Google Maps embed URL)', max_length=500, null=True, verbose_name='Map Embed URL')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of image URLs for the gallery section', verbose_name='Gallery Images')),
                ('testimonials', models.JSONField(blank=True, default=list, help_text='List of testimonials', verbose_name='Testimonials')),
                ('social_links', models.JSONField(blank=True, default=list, help_text='List of social media links', verbose_name='Social Links')),
                ('sample_url', models.SlugField(blank=True, help_text='Unique URL-friendly identifier (leave blank to auto-generate)', max_length=100, unique=True, verbose_name='Sample URL')),
                ('claimed', models.BooleanField(default=False, verbose_name='Claimed')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Claimed At')),
                ('contact_status', models.CharField(choices=[('notContacted', 'Not Contacted'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('notInterested', 'Not Interested'), ('subscribed', 'Subscribed')], default='notContacted', max_length=20, verbose_name='Contact Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salons',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier (leave blank to auto-generate)', max_length=120, unique=True, verbose_name='Template Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('preview_image', models.ImageField(blank=True, default='media/default.png', null=True, upload_to='template_previews/', verbose_name='Preview Image')),
                ('primary_color', models.CharField(blank=True, help_text='Primary color hex code (e.g., #RRGGBB)', max_length=7, null=True, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(blank=True, help_text='Secondary color hex code (e.g., #RRGGBB)', max_length=7, null=True, verbose_name='Secondary Color')),
                ('font_family', models.CharField(blank=True, help_text='CSS font-family string (e.g., "Poppins", sans-serif)', max_length=100, null=True, verbose_name='Font Family')),
                ('background_color', models.CharField(blank=True, help_text='Background color hex code (e.g., #RRGGBB)', max_length=7, null=True, verbose_name='Background Color')),
                ('text_color', models.CharField(blank=True, help_text='Text color hex code (e.g., #RRGGBB)', max_length=7, null=True, verbose_name='Text Color')),
                ('default_cover_image', models.ImageField(blank=True, null=True, upload_to='template_defaults/', verbose_name='Default Cover Image')),
                ('default_about_image', models.ImageField(blank=True, null=True, upload_to='template_defaults/', verbose_name='Default About Image')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Features')),
                ('is_mobile_optimized', models.BooleanField(default=True, verbose_name='Is Mobile Optimized')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
    ]
