# Generated by Django 5.2 on 2025-05-04 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('preview_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_mobile_optimized', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(help_text='e.g., City, State or Neighborhood', max_length=200)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('services', models.JSONField(blank=True, default=list, help_text="List of services, e.g., ['Manicure - $30', 'Pedicure - $45']")),
                ('opening_hours', models.TextField(blank=True, help_text='e.g., Mon-Fri: 9am-7pm\\nSat: 10am-5pm', null=True)),
                ('sample_url', models.SlugField(blank=True, help_text='Unique URL-friendly identifier (leave blank to auto-generate)', max_length=100, unique=True)),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('contact_status', models.CharField(choices=[('notContacted', 'Not Contacted'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('notInterested', 'Not Interested'), ('subscribed', 'Subscribed')], default='notContacted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_salons', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salons.template')),
            ],
        ),
    ]
