# Generated by Django 5.2 on 2025-05-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='salon_about/'),
        ),
        migrations.AddField(
            model_name='salon',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='salon_covers/'),
        ),
    ]
