# Generated by Django 5.2 on 2025-05-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_salon_about_image_salon_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Hex color code for background', max_length=7),
        ),
        migrations.AddField(
            model_name='template',
            name='font_family',
            field=models.CharField(default="'Poppins', sans-serif", help_text='CSS font-family string', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='primary_color',
            field=models.CharField(default='#f43f5e', help_text='Hex color code for primary theme color', max_length=7),
        ),
        migrations.AddField(
            model_name='template',
            name='secondary_color',
            field=models.CharField(default='#f9a8d4', help_text='Hex color code for secondary theme color', max_length=7),
        ),
        migrations.AddField(
            model_name='template',
            name='text_color',
            field=models.CharField(default='#333333', help_text='Hex color code for general text', max_length=7),
        ),
    ]
