# Generated by Django 5.2 on 2025-05-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='template',
            name='default_about_image',
        ),
        migrations.RemoveField(
            model_name='template',
            name='default_cover_image',
        ),
        migrations.RemoveField(
            model_name='template',
            name='features',
        ),
        migrations.RemoveField(
            model_name='template',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='template',
            name='is_mobile_optimized',
        ),
        migrations.RemoveField(
            model_name='template',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='template',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='template',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='template',
            name='text_color',
        ),
    ]
