# Generated by Django 5.2 on 2025-05-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_template_background_color_template_font_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='template',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='template',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='template',
            name='preview_image_url',
        ),
        migrations.RemoveField(
            model_name='template',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='template',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='template',
            name='text_color',
        ),
        migrations.AddField(
            model_name='template',
            name='preview_image',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='template_previews/'),
        ),
    ]
