# Generated by Django 5.2 on 2025-05-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_remove_salon_about_image_remove_salon_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='preview_image',
            field=models.ImageField(blank=True, default='/default.png', null=True, upload_to='media/'),
        ),
    ]
