# Generated by Django 5.2 on 2025-05-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_template_options_template_preview_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AddField(
            model_name='template',
            name='background_color',
            field=models.CharField(blank=True, help_text='Background color hex code (e.g., #RRGGBB)', max_length=7, null=True, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='template',
            name='default_about_image',
            field=models.ImageField(blank=True, null=True, upload_to='template_defaults/', verbose_name='Default About Image'),
        ),
        migrations.AddField(
            model_name='template',
            name='default_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='template_defaults/', verbose_name='Default Cover Image'),
        ),
        migrations.AddField(
            model_name='template',
            name='features',
            field=models.JSONField(blank=True, default=dict, verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='template',
            name='font_family',
            field=models.CharField(blank=True, help_text='CSS font-family string (e.g., "Poppins", sans-serif)', max_length=100, null=True, verbose_name='Font Family'),
        ),
        migrations.AddField(
            model_name='template',
            name='is_mobile_optimized',
            field=models.BooleanField(default=True, verbose_name='Is Mobile Optimized'),
        ),
        migrations.AddField(
            model_name='template',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Primary color hex code (e.g., #RRGGBB)', max_length=7, null=True, verbose_name='Primary Color'),
        ),
        migrations.AddField(
            model_name='template',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Secondary color hex code (e.g., #RRGGBB)', max_length=7, null=True, verbose_name='Secondary Color'),
        ),
        migrations.AddField(
            model_name='template',
            name='text_color',
            field=models.CharField(blank=True, help_text='Text color hex code (e.g., #RRGGBB)', max_length=7, null=True, verbose_name='Text Color'),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='template',
            name='preview_image',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='template_previews/', verbose_name='Preview Image'),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL-friendly identifier (leave blank to auto-generate)', max_length=120, unique=True, verbose_name='Template Slug'),
        ),
        migrations.AlterField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
