# Generated by Django 5.2 on 2025-05-11 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_alter_template_options_template_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='booking_url',
            field=models.URLField(blank=True, help_text='Online booking URL', null=True, verbose_name='Booking URL'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='footer_about',
            field=models.TextField(blank=True, help_text='About text in footer', null=True, verbose_name='Footer About'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for gallery', verbose_name='Gallery Images'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='gallery_tagline',
            field=models.CharField(blank=True, help_text='Gallery header description', max_length=255, null=True, verbose_name='Gallery Tagline'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='gallery_url',
            field=models.URLField(blank=True, help_text='Full gallery page URL', null=True, verbose_name='Gallery URL'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle', max_length=255, null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Map embed URL', max_length=500, null=True, verbose_name='Map Embed URL'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='services',
            field=models.JSONField(blank=True, default=list, help_text='List of services', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='services_tagline',
            field=models.CharField(blank=True, help_text='Services header description', max_length=255, null=True, verbose_name='Services Tagline'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='services_url',
            field=models.URLField(blank=True, help_text='Full services menu URL', null=True, verbose_name='Services URL'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons', to='salons.template', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='default_about_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Default About Image URL'),
        ),
        migrations.AlterField(
            model_name='template',
            name='default_cover_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Default Cover Image URL'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='features',
            field=models.JSONField(blank=True, default=dict, verbose_name='Template Features'),
        ),
        migrations.AlterField(
            model_name='template',
            name='font_family',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Font Family'),
        ),
        migrations.AlterField(
            model_name='template',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/previews/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='template',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Secondary Color'),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='text_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Text Color'),
        ),
        migrations.AlterField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
