# Generated by Django 5.2 on 2025-05-09 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Website Visit',
                'verbose_name_plural': 'Website Visits',
                'ordering': ['-timestamp'],
            },
        ),
    ]
